name: Build

on:
  push:
    paths-ignore:
    - README.md
  schedule:
  - cron: "0 0 * * 0"

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v4

    - name: build cat
      run: |
            cd 2024/labs-2024-10-14/CAT
            gcc -Wall -Wextra -std=c99 main.c
    - name: run cat
      run: |
            cd 2024/labs-2024-10-14/CAT
            ./a.out /etc/passwd > out1
            cat /etc/passwd > out2
            diff out1 out2
            echo $?