name: Build

on:
  push:
    paths-ignore:
    - README.md
  schedule:
  - cron: "0 0 * * 0"

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v4
    - name: build liba_libb
      run: |
            cd 2024/labs-2024-10-07/liba_libb
            make
    - name: run liba_libb
      run: |
            cd 2024/labs-2024-10-07/liba_libb
            ./main uuuy