name: Build

on:
  push:
    paths-ignore:
    - README.md
  schedule:
  - cron: "0 0 * * 0"

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v4
    - name: build le_be_system
      run: gcc -Wall -Wextra -std=c99 ./2024/labs-2024-09-30/le_be_system/main.c
    - name: run le_be_system
      run: ./2024/labs-2024-09-30/le_be_system/a.out